### ISSUE TITLE
Application Factory step `TypeError: 'Celery' object is not callable`

### ISSUE THREAD

**Issue by scarroll32** [testdrivenio/flask-celery-project#4]
I'm following the course and am at the step of the [Manual Test](https://testdriven.io/courses/flask-celery/app-factory/#H-7-manual-test) step of [Application Factory](https://testdriven.io/courses/flask-celery/app-factory/)

I am getting this error and cannot move past it, as far as I can see the code is identical to the course code. 

```python
env ❯ celery -A app.celery worker --loglevel=info
Usage: celery [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for '-A' / '--app':
Unable to load celery application.
While trying to load the module app.celery the following error occurred:
Traceback (most recent call last):
  File "/Users/sean/src/testdriven/flask-celery-project/env/lib/python3.9/site-packages/celery/bin/celery.py", line 53, in convert
    return find_app(value)
  File "/Users/sean/src/testdriven/flask-celery-project/env/lib/python3.9/site-packages/celery/app/utils.py", line 384, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/Users/sean/src/testdriven/flask-celery-project/env/lib/python3.9/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/Users/sean/src/testdriven/flask-celery-project/env/lib/python3.9/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
    return imp(module, package=package)
  File "/Users/sean/.pyenv/versions/3.9.2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sean/src/testdriven/flask-celery-project/app.py", line 4, in <module>
    celery = ext_celery.celery()
  File "/Users/sean/src/testdriven/flask-celery-project/env/lib/python3.9/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
TypeError: 'Celery' object is not callable
```

app.py
```python
from project import create_app, ext_celery

app = create_app()
celery = ext_celery.celery()
```

project/__init__.py
```python
import os

from flask import Flask
from flask_celeryext import FlaskCeleryExt
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from project.celery_utils import make_celery
from project.config import config

# instantiate the extensions
db = SQLAlchemy()
migrate = Migrate()
ext_celery = FlaskCeleryExt(create_celery_app=make_celery)

def create_app(config_name=None):
    if config_name is None:
        config_name = os.environ.get("FLASK_CONFIG", "development")

    # instantiate the app
    app = Flask(__name__)

    # set config
    app.config.from_object(config[config_name])

    # set up extensions
    db.init_app(app)
    migrate.init_app(app, db)
    ext_celery.init_app(app)

    # register blueprints
    from project.users import users_blueprint
    app.register_blueprint(users_blueprint)

    # shell context for flask cli
    @app.shell_context_processor
    def ctx():
        return {"app": app, "db": db}

    return app
```

project/celery_utls.py
```python
from celery import current_app as current_celery_app

def make_celery(app):
    celery = current_celery_app
    celery.config_from_object(app.config, namespace="CELERY")

    return celery
```

project/config.py
```python
import os
from pathlib import Path

class BaseConfig:
    """Base configuration"""
    BASE_DIR = Path(__file__).parent.parent

    TESTING = False
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_DATABASE_URI = os.environ.get("DATABASE_URL", f"sqlite:///{BASE_DIR}/db.sqlite3")

    CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', "redis://127.0.0.1:6379/0")
    CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis:://127.0.0.1:6379/0")

class DevelopmentConfig(BaseConfig):
    """Development configuration"""
    DEBUG = True

class ProductionConfig(BaseConfig):
    """Production configuration"""
    DEBUG = False

config = {
    "development": DevelopmentConfig,
    "production": ProductionConfig,
}
```

**Comment by scarroll32** [comment]
Can you help with this @michael-yin ?

**Comment by michael-yin** [comment]
@scarroll32 

I will check this issue in a bit (it is my dinner time)

Thx.

**Comment by scarroll32** [comment]
> @scarroll32
> 
> I will check this issue in a bit (it is my dinner time)
> 
> Thx.

Thank you!

**Comment by scarroll32** [comment]
@michael-yin please see the full code here https://github.com/scarroll32/flask-celery-project

**Comment by scarroll32** [comment]
I think I found it

app.py
```python
from project import create_app, ext_celery

app = create_app()
celery = ext_celery.celery
```

**Comment by scarroll32** [comment]
@michael-yin I found the problem, thank you.

I would be really helpful if there was a branch of the code at the end of each chapter on this repo.
